// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCP8K8k0XPkPYSAJOkVWoSl7fSl7pDWGv0',
    appId: '1:912816825857:web:15accec2c38d3390d9c200',
    messagingSenderId: '912816825857',
    projectId: 'basic-crud-b2ec9',
    authDomain: 'basic-crud-b2ec9.firebaseapp.com',
    storageBucket: 'basic-crud-b2ec9.appspot.com',
    measurementId: 'G-TBMR3JPGML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqWvJ8xp3HqEJFROeCXR43xLzS7VgkYYQ',
    appId: '1:912816825857:android:33d451a6d88916aad9c200',
    messagingSenderId: '912816825857',
    projectId: 'basic-crud-b2ec9',
    storageBucket: 'basic-crud-b2ec9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD36fLwc2uK9Vw0fuNFMobIDNTUahHzoco',
    appId: '1:912816825857:ios:b869d4b3da303cb1d9c200',
    messagingSenderId: '912816825857',
    projectId: 'basic-crud-b2ec9',
    storageBucket: 'basic-crud-b2ec9.appspot.com',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD36fLwc2uK9Vw0fuNFMobIDNTUahHzoco',
    appId: '1:912816825857:ios:63c1d31a3aa84588d9c200',
    messagingSenderId: '912816825857',
    projectId: 'basic-crud-b2ec9',
    storageBucket: 'basic-crud-b2ec9.appspot.com',
    iosBundleId: 'com.example.crud.RunnerTests',
  );
}
